package com.lifecyclehealth.lifecyclehealth.dto;

/**
 * Created by vaibhavi on 13-11-2017.
 */

public class ChangePasswordAutogeneratedDto {

    private String oldPassword;
    private String newPassword;
    private String emailId;

    public String getOldPassword() {
        return oldPassword;
    }

    public void setOldPassword(String oldPassword) {
        this.oldPassword = oldPassword;
    }

    public String getNewPassword() {
        return newPassword;
    }

    public void setNewPassword(String newPassword) {
        this.newPassword = newPassword;
    }

    public String getEmailId() {
        return emailId;
    }

    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }

    @Override
    public String toString() {
        return "ChangePasswordAutogeneratedDto{" +
                "oldPassword='" + oldPassword + '\'' +
                ", newPassword='" + newPassword + '\'' +
                ", emailId='" + emailId + '\'' +
                '}';
    }
}
